[build]
  base = "apps/btc-futures"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Optional: per-branch settings
#[context.production]
#  environment = { NODE_VERSION = "18" }
#[context.deploy-preview]
#  environment = { NODE_VERSION = "18" }
